# Generated by Django 6.0.3 on 2026-04-11 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("work", "На работе"),
                            ("vacation", "В отпуске"),
                            ("sick_leave", "На больничном"),
                            ("truancy", "Прогул"),
                        ],
                        default="work",
                        null=True,
                        verbose_name="Статус сотрудника",
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Оклад"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Электронная почта"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Фамилия"
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Должность"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Адрес проживания",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="День рождения"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, verbose_name="Последний вход"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photo/avatars/",
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=100,
                        verbose_name="Токен пользователя",
                    ),
                ),
                (
                    "can_login",
                    models.BooleanField(
                        default=False, verbose_name="Возможность входа в систему"
                    ),
                ),
                (
                    "department",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="departments.department",
                        verbose_name="Отдел",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="профиль сотрудника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["id"],
            },
        ),
    ]
